require("hzerbini.lsp.astro")
require("hzerbini.lsp.dart")
require("hzerbini.lsp.emmet")
require("hzerbini.lsp.go")
require("hzerbini.lsp.html")
require("hzerbini.lsp.jsonls")
require("hzerbini.lsp.lua")
require("hzerbini.lsp.markdown")
require("hzerbini.lsp.php")
require("hzerbini.lsp.tailwindcss")
require("hzerbini.lsp.tsserver")
require("hzerbini.lsp.yaml")
-- require("hzerbini.lsp.vuels")
require("hzerbini.lsp.prisma")
