#!/bin/zsh

pass_list=`pass keepassxc | keepassxc-cli ls -R $HOME/Dropbox/Passwords.kdbx | sed '/\/$/d' | sed -e 's/^[ \t]*//'`

if [ -z "$pass_list" ]; then
    exit 0;
fi

choice=`echo $pass_list | fzf`

pass keepassxc | keepassxc-cli clip -q $HOME/Dropbox/Passwords.kdbx $choice
